package uy.com.bbva.services.orchestrator.model.storage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private uy.com.bbva.services.orchestrator.model.storage.AccountDocumentType accountDocumentType;

	public Account() {
	}

	private String id;
	private String name;
	private String number;
	private String isSalaryPayment;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getIsSalaryPayment() {
		return isSalaryPayment;
	}

	public void setIsSalaryPayment(String isSalaryPayment) {
		this.isSalaryPayment = isSalaryPayment;
	}

	public uy.com.bbva.services.orchestrator.model.storage.AccountDocumentType getAccountDocumentType() {
		return this.accountDocumentType;
	}

	public void setAccountDocumentType(
			uy.com.bbva.services.orchestrator.model.storage.AccountDocumentType accountDocumentType) {
		this.accountDocumentType = accountDocumentType;
	}

	public Account(uy.com.bbva.services.orchestrator.model.storage.AccountDocumentType accountDocumentType,
			java.lang.String id, java.lang.String name,
			java.lang.String number, java.lang.String isSalaryPayment) {
		this.accountDocumentType = accountDocumentType;
		this.id = id;
		this.name = name;
		this.number = number;
		this.isSalaryPayment = isSalaryPayment;
	}

}