package uy.com.bbva.services.orchestrator.model.storage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BoxAccount implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<uy.com.bbva.services.orchestrator.model.storage.Account> accounts;
	private uy.com.bbva.services.orchestrator.model.storage.Branch branch;
	private java.util.Date lastShippingDate;
	private uy.com.bbva.services.orchestrator.model.storage.Sector sector;
	private uy.com.bbva.services.orchestrator.model.storage.Status status;

	private uy.com.bbva.services.orchestrator.model.storage.Status shippingRelationshipStatus;

	public BoxAccount() {
	}

	private String id;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public java.util.List<uy.com.bbva.services.orchestrator.model.storage.Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.Account> accounts) {
		this.accounts = accounts;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Branch getBranch() {
		return this.branch;
	}

	public void setBranch(
			uy.com.bbva.services.orchestrator.model.storage.Branch branch) {
		this.branch = branch;
	}

	public java.util.Date getLastShippingDate() {
		return this.lastShippingDate;
	}

	public void setLastShippingDate(java.util.Date lastShippingDate) {
		this.lastShippingDate = lastShippingDate;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Sector getSector() {
		return this.sector;
	}

	public void setSector(
			uy.com.bbva.services.orchestrator.model.storage.Sector sector) {
		this.sector = sector;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Status getStatus() {
		return this.status;
	}

	public void setStatus(
			uy.com.bbva.services.orchestrator.model.storage.Status status) {
		this.status = status;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Status getShippingRelationshipStatus() {
		return this.shippingRelationshipStatus;
	}

	public void setShippingRelationshipStatus(
			uy.com.bbva.services.orchestrator.model.storage.Status shippingRelationshipStatus) {
		this.shippingRelationshipStatus = shippingRelationshipStatus;
	}

	public BoxAccount(
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.Account> accounts,
			uy.com.bbva.services.orchestrator.model.storage.Branch branch,
			java.util.Date lastShippingDate,
			uy.com.bbva.services.orchestrator.model.storage.Sector sector,
			uy.com.bbva.services.orchestrator.model.storage.Status status,
			uy.com.bbva.services.orchestrator.model.storage.Status shippingRelationshipStatus,
			java.lang.String id) {
		this.accounts = accounts;
		this.branch = branch;
		this.lastShippingDate = lastShippingDate;
		this.sector = sector;
		this.status = status;
		this.shippingRelationshipStatus = shippingRelationshipStatus;
		this.id = id;
	}

}