package uy.com.bbva.services.orchestrator.model.storage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BoxInternalDocument implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<uy.com.bbva.services.orchestrator.model.storage.InternalDocument> internalDocuments;
	private java.util.Date expirationDate;
	private uy.com.bbva.services.orchestrator.model.storage.Status status;
	private java.util.Date lastShippingDate;
	private uy.com.bbva.services.orchestrator.model.storage.Branch branch;
	private uy.com.bbva.services.orchestrator.model.storage.Sector sector;

	private uy.com.bbva.services.orchestrator.model.storage.Status shippingRelationshipStatus;

	public BoxInternalDocument() {
	}

	private String id;
	private String description;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public java.util.List<uy.com.bbva.services.orchestrator.model.storage.InternalDocument> getInternalDocuments() {
		return this.internalDocuments;
	}

	public void setInternalDocuments(
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.InternalDocument> internalDocuments) {
		this.internalDocuments = internalDocuments;
	}

	public java.util.Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(java.util.Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Status getStatus() {
		return this.status;
	}

	public void setStatus(
			uy.com.bbva.services.orchestrator.model.storage.Status status) {
		this.status = status;
	}

	public java.util.Date getLastShippingDate() {
		return this.lastShippingDate;
	}

	public void setLastShippingDate(java.util.Date lastShippingDate) {
		this.lastShippingDate = lastShippingDate;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Branch getBranch() {
		return this.branch;
	}

	public void setBranch(
			uy.com.bbva.services.orchestrator.model.storage.Branch branch) {
		this.branch = branch;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Sector getSector() {
		return this.sector;
	}

	public void setSector(
			uy.com.bbva.services.orchestrator.model.storage.Sector sector) {
		this.sector = sector;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Status getShippingRelationshipStatus() {
		return this.shippingRelationshipStatus;
	}

	public void setShippingRelationshipStatus(
			uy.com.bbva.services.orchestrator.model.storage.Status shippingRelationshipStatus) {
		this.shippingRelationshipStatus = shippingRelationshipStatus;
	}

	public BoxInternalDocument(
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.InternalDocument> internalDocuments,
			java.util.Date expirationDate,
			uy.com.bbva.services.orchestrator.model.storage.Status status,
			java.util.Date lastShippingDate,
			uy.com.bbva.services.orchestrator.model.storage.Branch branch,
			uy.com.bbva.services.orchestrator.model.storage.Sector sector,
			uy.com.bbva.services.orchestrator.model.storage.Status shippingRelationshipStatus,
			java.lang.String id, java.lang.String description) {
		this.internalDocuments = internalDocuments;
		this.expirationDate = expirationDate;
		this.status = status;
		this.lastShippingDate = lastShippingDate;
		this.branch = branch;
		this.sector = sector;
		this.shippingRelationshipStatus = shippingRelationshipStatus;
		this.id = id;
		this.description = description;
	}

}