package uy.com.bbva.services.orchestrator.model.storage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Branch implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean isMetropolitanBranch;

	public Branch() {
	}

	private String id;
	private String name;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public java.lang.Boolean getIsMetropolitanBranch() {
		return this.isMetropolitanBranch;
	}

	public void setIsMetropolitanBranch(java.lang.Boolean isMetropolitanBranch) {
		this.isMetropolitanBranch = isMetropolitanBranch;
	}

	public Branch(java.lang.Boolean isMetropolitanBranch, java.lang.String id,
			java.lang.String name) {
		this.isMetropolitanBranch = isMetropolitanBranch;
		this.id = id;
		this.name = name;
	}
	
	  public Branch(Branch b){
        this.id = b.id;
        this.name = b.name;
        this.isMetropolitanBranch = b.isMetropolitanBranch;
    }

}