package uy.com.bbva.services.orchestrator.model.storage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shipping implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxAccount> boxAccounts;
	private java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxInternalDocument> boxInternalDocuments;
	private java.lang.String type;
	private java.util.Date shippingDate;
	private uy.com.bbva.services.orchestrator.model.storage.Status status;
	private User user;
	private uy.com.bbva.services.orchestrator.model.storage.Branch branch;
	private uy.com.bbva.services.orchestrator.model.storage.Sector sector;

	public Shipping() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxAccount> getBoxAccounts() {
		return this.boxAccounts;
	}

	public void setBoxAccounts(
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxAccount> boxAccounts) {
		this.boxAccounts = boxAccounts;
	}

	public java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxInternalDocument> getBoxInternalDocuments() {
		return this.boxInternalDocuments;
	}

	public void setBoxInternalDocuments(
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxInternalDocument> boxInternalDocuments) {
		this.boxInternalDocuments = boxInternalDocuments;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.util.Date getShippingDate() {
		return this.shippingDate;
	}

	public void setShippingDate(java.util.Date shippingDate) {
		this.shippingDate = shippingDate;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Status getStatus() {
		return this.status;
	}

	public void setStatus(
			uy.com.bbva.services.orchestrator.model.storage.Status status) {
		this.status = status;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Branch getBranch() {
		return this.branch;
	}

	public void setBranch(
			uy.com.bbva.services.orchestrator.model.storage.Branch branch) {
		this.branch = branch;
	}

	public uy.com.bbva.services.orchestrator.model.storage.Sector getSector() {
		return this.sector;
	}

	public void setSector(
			uy.com.bbva.services.orchestrator.model.storage.Sector sector) {
		this.sector = sector;
	}

	public Shipping(Shipping s) {
		this.id = s.id;
		this.boxAccounts = new java.util.ArrayList<>(s.boxAccounts);
		this.boxInternalDocuments = new java.util.ArrayList<>(
				s.boxInternalDocuments);
		this.type = s.type;
		this.shippingDate = s.shippingDate;
		this.status = s.status != null
				? new uy.com.bbva.services.orchestrator.model.storage.Status(
						s.status) : null;
		this.user = s.user;
		this.branch = s.branch != null
				? new uy.com.bbva.services.orchestrator.model.storage.Branch(
						s.branch) : null;
		this.sector = s.sector != null
				? new uy.com.bbva.services.orchestrator.model.storage.Sector(
						s.sector) : null;
	}

	public uy.com.bbva.services.orchestrator.model.storage.User getUser() {
		return this.user;
	}

	public void setUser(
			uy.com.bbva.services.orchestrator.model.storage.User user) {
		this.user = user;
	}

	public Shipping(
			java.lang.String id,
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxAccount> boxAccounts,
			java.util.List<uy.com.bbva.services.orchestrator.model.storage.BoxInternalDocument> boxInternalDocuments,
			java.lang.String type, java.util.Date shippingDate,
			uy.com.bbva.services.orchestrator.model.storage.Status status,
			uy.com.bbva.services.orchestrator.model.storage.User user,
			uy.com.bbva.services.orchestrator.model.storage.Branch branch,
			uy.com.bbva.services.orchestrator.model.storage.Sector sector) {
		this.id = id;
		this.boxAccounts = boxAccounts;
		this.boxInternalDocuments = boxInternalDocuments;
		this.type = type;
		this.shippingDate = shippingDate;
		this.status = status;
		this.user = user;
		this.branch = branch;
		this.sector = sector;
	}

}